import * as esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { cp, rm, mkdir, writeFile } from "fs/promises";
import { resolve } from "path";
import { homedir } from "os";
import globImport from "esbuild-plugin-glob-import";

import manifest from "./src/assets/manifest.stub.json";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProduction = process.env.NODE_ENV === "production";
const outdir = resolve(
    homedir(),
    "Documents/_privat/Gabriel/.obsidian/plugins/text-mapper/"
);

function cleanOutdir(outdir: string): esbuild.Plugin {
    return {
        name: "clean-outdir",
        setup: async () => {
            // Clean the output directory before building
            await rm(outdir, { recursive: true, force: true });
        },
    };
}

function copyStaticFiles(config: {
    inputdir: string;
    outdir: string;
}): esbuild.Plugin {
    return {
        name: "copy-static-files",
        setup: () => cp(config.inputdir, config.outdir, { recursive: true }),
    };
}

function buildObsidianManifest(outdir: string): esbuild.Plugin {
    return {
        name: "build-obisidian-manifest",
        setup(build) {
            const filePath = resolve(outdir, "manifest.json");

            build.onEnd(async () => {
                // TODO: Use git tags to set base version and only append timestamp for development
                manifest.version = [manifest.version, Date.now()].join(".");
                return writeFile(filePath, JSON.stringify(manifest));
            });
        },
    };
}

function toggleObsidianHotreload(outdir: string): esbuild.Plugin {
    return {
        name: "toggle-obsidian-hotreload",
        async setup() {
            // Set up auto reloading for development
            const filePath = resolve(outdir, ".hotreload");

            if (isProduction) {
                return rm(filePath, { force: true, recursive: true });
            } else {
                await mkdir(outdir, { recursive: true });
                return writeFile(filePath, "");
            }
        },
    };
}

// TODO: Check if the .css file must be "styles.css" and add plugin to rename it here in that case
const options = {
    banner: {
        js: banner,
    },
    entryPoints: ["./src/main.ts"],
    bundle: true,
    external: ["obsidian", "electron", ...builtins],
    format: "cjs",
    assetNames: "[name]",
    // TODO: Add support for resolving images, etc. as file urls with Obsidian syntax
    loader: {
        ".jpeg": "dataurl",
        ".jpg": "dataurl",
        ".png": "dataurl",
        ".svg": "dataurl",
        ".ttf": "dataurl",
        ".woff": "dataurl",
    },
    target: "es2018",
    logLevel: "info",
    sourcemap: isProduction ? false : "inline",
    treeShaking: true,
    outdir,
    plugins: [
        cleanOutdir(outdir),
        toggleObsidianHotreload(outdir),
        buildObsidianManifest(outdir),
        copyStaticFiles({ inputdir: "./static", outdir }),
        globImport({
            camelCase: false,
        }),
    ],
} satisfies esbuild.BuildOptions;

try {
    if (isProduction) {
        await esbuild.build(options);
    } else {
        const ctx = await esbuild.context(options);
        await ctx.watch();
    }
} catch (err) {
    console.error("Error while executing esbuild:", err);
    process.exit(1);
}
