import * as esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { cp, rm, writeFile } from "fs/promises";
import { resolve } from "path";
import { homedir } from "os";
import globImport from "esbuild-plugin-glob-import";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProduction = process.env.NODE_ENV === "production";
const outdir = resolve(
    homedir(),
    "Documents/_privat/Gabriel/.obsidian/plugins/text-mapper/"
);

// TODO: Check if the .css file must be "styles.css" and add plugin to rename it here in that case
const options = {
    banner: {
        js: banner,
    },
    entryPoints: ["./src/main.ts"],
    bundle: true,
    external: ["obsidian", "electron", ...builtins],
    format: "cjs",
    assetNames: "[name]",
    // TODO: Add support for resolving images, etc. as file urls with Obsidian syntax
    loader: {
        ".jpeg": "dataurl",
        ".jpg": "dataurl",
        ".png": "dataurl",
        ".svg": "dataurl",
        ".json": "copy",
        ".ttf": "dataurl",
        ".woff": "dataurl",
    },
    target: "es2018",
    logLevel: "info",
    sourcemap: isProduction ? false : "inline",
    treeShaking: true,
    outdir,
    plugins: [
        globImport({
            camelCase: false,
        }),
    ],
} satisfies esbuild.BuildOptions;

async function enableHotReload(outdir: string) {
    // Set up auto reloading for development
    const filePath = await resolve(outdir, ".hotreload");

    // Copy static files to the output directory
    await cp("./static", outdir, { recursive: true });

    if (isProduction) {
        return rm(filePath, { force: true });
    } else {
        return writeFile(filePath, "");
    }
}

try {
    if (isProduction) {
        await esbuild.build(options);
    } else {
        await enableHotReload(outdir);
        const ctx = await esbuild.context(options);
        await ctx.watch();
    }
} catch (err) {
    console.error("Error while executing esbuild:", err);
    process.exit(1);
}
